services:
    redis:
        hostname: "redis_cache"
        container_name: "redis_cache"
        image: "redis:7.0-alpine"
        ports:
        - "6379:6379"
        networks:
        - server
        volumes:
        - ./volume/redis:/data
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

    db:
        hostname: db
        container_name: mssql_db
        image: mcr.microsoft.com/mssql/server:2022-latest
        restart: no
        networks:
        - server
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: ${DB_PASSWORD}
            MSSQL_PID: "Express"
        ports:
            - "1433:1433"
        volumes:
            - ./volume/mssql:/var/opt/mssql


networks:
    server:
        driver: bridge
        name: server_network
